sudo: required
services:
  - docker
before_install: 
  - docker build -t nsfa/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run nsfa/react-test npm test -- --coverage

after_success: 
  - docker build -t nsfa/multi-client ./client
  - docker build -t nsfa/multi-nginx ./nginx
  - docker build -t nsfa/multi-server ./server 
  - docker build -t nsfa/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to docker hub

  - docker push nsfa/multi-client
  - docker push nsfa/multi-nginx
  - docker push nsfa/multi-server
  - docker push nsfa/multi-worker